name: Build OpenWrt for youku_yk-l1 (PassWall sing-box + zh-cn only)

on:
  workflow_dispatch:
    inputs:
      OPENWRT_BRANCH:
        description: "OpenWrt 稳定分支或标签（默认 openwrt-24.10，可填 v24.10.x）"
        default: "openwrt-24.10"
        required: true
      KEEP_CONFIG:
        description: "复用上次 .config（true/false）"
        default: "false"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      TZ: Asia/Shanghai
      # 可按需增删包；已包含 zh-cn/argon/wol/passwall/frpc/自动挂载相关
      EXTRA_PACKAGES: >
        luci
        luci-compat
        luci-app-wol
        luci-i18n-base-zh-cn
        luci-i18n-wol-zh-cn
        luci-theme-argon
        frpc
        luci-app-passwall
        luci-i18n-passwall-zh-cn
        sing-box
        v2ray-geoip v2ray-geosite
        block-mount kmod-usb-storage kmod-usb-storage-uas kmod-fs-ext4 ntfs-3g

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-distutils rsync unzip wget zlib1g-dev \
            file time ccache upx-ucl

      - name: Fetch OpenWrt
        run: |
          git clone https://github.com/openwrt/openwrt.git openwrt
          cd openwrt
          git fetch --tags --force
          git checkout "${{ github.event.inputs.OPENWRT_BRANCH || 'openwrt-24.10' }}"
          ./scripts/feeds update -a

      - name: Add 3rd-party feeds (PassWall / Automount / FRP / Argon)
        working-directory: openwrt
        run: |
          cat >> feeds.conf.default << 'EOF'

          # PassWall
          src-git passwall https://github.com/xiaorouji/openwrt-passwall

          # Automount
          src-git automount https://github.com/sirpdboy/automount

          # FRP (client only)
          src-git frp https://github.com/kuoruan/openwrt-frp

          # Argon theme
          src-git argon https://github.com/jerrykuku/luci-theme-argon
          EOF

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Create/restore .config (ramips/mt7620 -> youku_yk-l1)
        working-directory: openwrt
        run: |
          if [ "${{ github.event.inputs.KEEP_CONFIG }}" = "true" ] && [ -f ../.config.saved ]; then
            echo "Reusing previous .config"
            cp ../.config.saved .config
          else
            rm -f .config
            cat >> .config << 'EOF'
            CONFIG_TARGET_ramips=y
            CONFIG_TARGET_ramips_mt7620=y
            CONFIG_TARGET_PROFILE="youku_yk-l1"
            EOF

            # 预装软件包（来自 env.EXTRA_PACKAGES）
            for p in $EXTRA_PACKAGES; do
              echo "CONFIG_PACKAGE_${p}=y" >> .config
            done

            # —— 只保留 PassWall 的简体中文语言包，其它全部禁用 ——
            echo 'CONFIG_PACKAGE_luci-i18n-passwall-zh-cn=y' >> .config
            for lang in \
              ar bg bn ca cs da de el es et fa fi fr he hi hr hu id it ja ko ms nb-no nl pl pt pt-br ro ru sk sl sr sv th tr uk vi zh-tw \
            ; do
              echo "CONFIG_PACKAGE_luci-i18n-passwall-${lang}=n" >> .config
            done

            # —— PassWall 内核精简：只留 sing-box ——
            echo 'CONFIG_PACKAGE_sing-box=y' >> .config
            cat >> .config << 'EOF'
            CONFIG_PACKAGE_xray-core=n
            CONFIG_PACKAGE_v2ray-core=n
            CONFIG_PACKAGE_naiveproxy=n
            CONFIG_PACKAGE_hysteria=n
            CONFIG_PACKAGE_hysteria2=n
            CONFIG_PACKAGE_tuic-client=n
            CONFIG_PACKAGE_brook=n
            CONFIG_PACKAGE_trojan=n
            CONFIG_PACKAGE_trojan-go=n
            CONFIG_PACKAGE_shadowsocks-libev-ss-local=n
            CONFIG_PACKAGE_shadowsocks-libev-ss-redir=n
            CONFIG_PACKAGE_shadowsocks-rust-sslocal=n
            CONFIG_PACKAGE_shadowsocks-rust-ssredir=n
            CONFIG_PACKAGE_sing-box-with-plugins=n
            EOF

            # 仅客户端：不编译 frps
            echo 'CONFIG_PACKAGE_frps=n' >> .config

            # 体积优化（dnsmasq-full、关闭调试项）
            cat >> .config << 'EOF'
            # CONFIG_PACKAGE_dnsmasq is not set
            CONFIG_PACKAGE_dnsmasq-full=y
            CONFIG_DEBUG_KERNEL=n
            CONFIG_KERNEL_DEBUG_FS=n
            EOF
          fi

          make defconfig
          cp .config ../.config.saved

      - name: Default LuCI language & theme (zh_cn + argon)
        working-directory: openwrt
        run: |
          mkdir -p files/etc/config
          cat > files/etc/config/luci << 'EOF'
          config core 'main'
              option lang 'zh_cn'
              option mediaurlbase '/luci-static/argon'
          EOF

      - name: Enable ccache & download sources
        working-directory: openwrt
        run: |
          echo 'CONFIG_DEVEL=y' >> .config
          echo 'CONFIG_CCACHE=y' >> .config
          make defconfig
          make download -j$(nproc)

      - name: Build
        working-directory: openwrt
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Package outputs
        run: |
          mkdir -p output
          cp -av openwrt/bin/targets/ramips/mt7620/* output/ || true
          cp -av .config.saved output/seed.config
          cp -av openwrt/feeds.conf.default output/feeds.conf.default

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-youku_yk-l1-singbox-zhcn
          path: output
