name: Build OpenWrt for youku_yk-l1 (PassWall sing-box + zh-cn only)

on:
  workflow_dispatch:
    inputs:
      OPENWRT_BRANCH:
        description: "OpenWrt 稳定分支或标签（默认 openwrt-24.10，可填 v24.10.x）"
        default: "openwrt-24.10"
        required: true
      KEEP_CONFIG:
        description: "复用上次 .config（true/false）"
        default: "false"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      TZ: Asia/Shanghai
      # 关键：把临时目录改到工作区，避免 /tmp 爆满
      TMPDIR: ${{ github.workspace }}/tmp
      EXTRA_PACKAGES: >
        luci
        luci-compat
        luci-app-wol
        luci-i18n-base-zh-cn
        luci-i18n-wol-zh-cn
        luci-theme-argon
        frpc
        luci-app-passwall
        luci-i18n-passwall-zh-cn
        sing-box
        v2ray-geoip v2ray-geosite
        block-mount kmod-usb-storage kmod-usb-storage-uas kmod-fs-ext4 ntfs-3g

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Free disk space (dotnet / android / ghc)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo docker image prune -af || true
          df -h

      - name: Prepare tmp dir & show env
        run: |
          mkdir -p "${TMPDIR}"
          echo "TMPDIR=${TMPDIR}"
          df -h
          echo "CPU cores: $(nproc)"

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-distutils rsync unzip wget zlib1g-dev \
            file time ccache upx-ucl
          df -h

      - name: Fetch OpenWrt
        run: |
          git clone https://github.com/openwrt/openwrt.git openwrt
          cd openwrt
          git fetch --tags --force
          git checkout "${{ github.event.inputs.OPENWRT_BRANCH || 'openwrt-24.10' }}"

      - name: Add & update feeds (with retry)
        working-directory: openwrt
        run: |
          set -e

          # 如果默认 feeds 被意外缺失，恢复到官方默认
          if ! grep -q '^src-git luci ' feeds.conf.default 2>/dev/null; then
            cat > feeds.conf.default << 'EOF'
          src-git packages https://git.openwrt.org/feed/packages.git
          src-git luci https://git.openwrt.org/project/luci.git
          src-git routing https://git.openwrt.org/feed/routing.git
          src-git telephony https://git.openwrt.org/feed/telephony.git
          EOF
          fi

          # 追加第三方 feeds（PassWall 主仓库 + packages、Automount、FRP、Argon）
          {
            echo ""
            echo "# PassWall"
            echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall"
            echo ""
            echo "# PassWall packages (chinadns-ng / dns2socks / tcping etc.)"
            echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages"
            echo ""
            echo "# Automount"
            echo "src-git automount https://github.com/sirpdboy/automount"
            echo ""
            echo "# FRP (client only)"
            echo "src-git frp https://github.com/kuoruan/openwrt-frp"
            echo ""
            echo "# Argon theme"
            echo "src-git argon https://github.com/jerrykuku/luci-theme-argon"
          } >> feeds.conf.default

          # 带重试的 update/install
          try_update() {
            for i in 1 2 3; do
              echo "== Feeds update attempt $i =="
              ./scripts/feeds update -a && return 0
              sleep 5
            done
            return 1
          }
          try_install() {
            for i in 1 2 3; do
              echo "== Feeds install attempt $i =="
              ./scripts/feeds install -a && return 0
              sleep 5
            done
            return 1
          }

          try_update
          try_install

          # 校验目录存在
          for d in luci routing telephony packages passwall passwall_packages automount frp argon; do
            if [ ! -d "feeds/$d" ]; then
              echo "::error ::feeds/$d 不存在，feeds 更新失败"
              ls -la feeds || true
              exit 1
            fi
          done

          ls -la feeds
          df -h

      - name: Create/restore .config (ramips/mt7620 -> youku_yk-l1 ONLY)
        working-directory: openwrt
        run: |
          if [ "${{ github.event.inputs.KEEP_CONFIG }}" = "true" ] && [ -f ../.config.saved ]; then
            echo "Reusing previous .config"
            cp ../.config.saved .config
          else
            rm -f .config
            {
              echo "CONFIG_TARGET_ramips=y"
              echo "CONFIG_TARGET_ramips_mt7620=y"
              # 只编译 youku_yk-l1，关闭多 Profile
              echo "CONFIG_TARGET_MULTI_PROFILE=n"
            } >> .config

            # 显式仅启用当前设备
            sed -i '/^CONFIG_TARGET_DEVICE_ramips_mt7620_DEVICE_/d' .config
            echo 'CONFIG_TARGET_DEVICE_ramips_mt7620_DEVICE_youku_yk-l1=y' >> .config

            # 预装软件包（来自 env.EXTRA_PACKAGES）
            for p in $EXTRA_PACKAGES; do
              echo "CONFIG_PACKAGE_${p}=y" >> .config
            done

            # 只保留 PassWall 的简体中文语言包，其它禁用
            echo 'CONFIG_PACKAGE_luci-i18n-passwall-zh-cn=y' >> .config
            for lang in ar bg bn ca cs da de el es et fa fi fr he hi hr hu id it ja ko ms nb-no nl pl pt pt-br ro ru sk sl sr sv th tr uk vi zh-tw; do
              echo "CONFIG_PACKAGE_luci-i18n-passwall-${lang}=n" >> .config
            done

            # PassWall 内核精简：只留 sing-box
            echo 'CONFIG_PACKAGE_sing-box=y' >> .config
            {
              echo 'CONFIG_PACKAGE_xray-core=n'
              echo 'CONFIG_PACKAGE_v2ray-core=n'
              echo 'CONFIG_PACKAGE_naiveproxy=n'
              echo 'CONFIG_PACKAGE_hysteria=n'
              echo 'CONFIG_PACKAGE_hysteria2=n'
              echo 'CONFIG_PACKAGE_tuic-client=n'
              echo 'CONFIG_PACKAGE_brook=n'
              echo 'CONFIG_PACKAGE_trojan=n'
              echo 'CONFIG_PACKAGE_trojan-go=n'
              echo 'CONFIG_PACKAGE_shadowsocks-libev-ss-local=n'
              echo 'CONFIG_PACKAGE_shadowsocks-libev-ss-redir=n'
              echo 'CONFIG_PACKAGE_shadowsocks-rust-sslocal=n'
              echo 'CONFIG_PACKAGE_shadowsocks-rust-ssredir=n'
              echo 'CONFIG_PACKAGE_sing-box-with-plugins=n'
            } >> .config

            # PassWall 的三个工具依赖（避免 WARNING / 缺包）
            echo 'CONFIG_PACKAGE_chinadns-ng=y' >> .config
            echo 'CONFIG_PACKAGE_dns2socks=y' >> .config
            echo 'CONFIG_PACKAGE_tcping=y' >> .config

            # 仅客户端：不编译 frps
            echo 'CONFIG_PACKAGE_frps=n' >> .config

            # 体积优化
            {
              echo '# CONFIG_PACKAGE_dnsmasq is not set'
              echo 'CONFIG_PACKAGE_dnsmasq-full=y'
              echo 'CONFIG_DEBUG_KERNEL=n'
              echo 'CONFIG_KERNEL_DEBUG_FS=n'
            } >> .config
          fi

          make defconfig
          cp .config ../.config.saved
          df -h

      - name: Default LuCI language & theme (zh_cn + argon)
        working-directory: openwrt
        run: |
          mkdir -p files/etc/config
          {
            echo "config core 'main'"
            echo "    option lang 'zh_cn'"
            echo "    option mediaurlbase '/luci-static/argon'"
          } > files/etc/config/luci

      - name: Enable ccache & download sources
        working-directory: openwrt
        run: |
          echo 'CONFIG_DEVEL=y' >> .config
          echo 'CONFIG_CCACHE=y' >> .config
          make defconfig
          make download -j$(nproc)
          df -h

      - name: Build
        working-directory: openwrt
        run: |
          set -e
          echo "Start build with -j$(nproc)"
          if ! make -j$(nproc); then
            echo "Parallel build failed, retry with -j1 V=s"
            make -j1 V=s
          fi

      - name: Package outputs
        run: |
          mkdir -p output
          cp -av openwrt/bin/targets/ramips/mt7620/* output/ || true
          cp -av .config.saved output/seed.config
          cp -av openwrt/feeds.conf.default output/feeds.conf.default
          df -h

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-youku_yk-l1-singbox-zhcn
          path: output
